version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - "8080:8080"
    environment:
      - QUARKUS_DATASOURCE_DB_KIND=postgresql
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://db:5432/componentdb
      - QUARKUS_DATASOURCE_USERNAME=admin
      - QUARKUS_DATASOURCE_PASSWORD=admin
    depends_on:
      - db
    networks:
      - quarkus-network

  db:
    image: postgres
    container_name: postgres-db
    environment:
      POSTGRES_DB: componentdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - quarkus-network

networks:
  quarkus-network:

volumes:
  db-data:
